<?php
/**
 * @file
 *
 * Hooks and helpers for Password Requirements
 */

/**
 * Implements hook_permission().
 */
function password_requirements_permission() {
  $permissions = array(
    'administer password requirements' => array(
      'title' => t('Administer Password Requirements'),
    ),
  );
  return $permissions;
}

/**
 * Implements hook_config_info().
 */
function password_requirements_config_info() {
  $info['password_requirements.settings'] = array(
    'label' => t('Password Requirements settings'),
    'group' => t('Configuration'),
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function password_requirements_menu() {
  $items = array();
  $items['ajax/people/password-requirements/check'] = array(
    'title' => 'Check password',
    'page callback' => 'password_requirements_ajax_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/people/password-requirements'] = array(
    'title' => 'Password Requirements settings',
    'description' => 'Manage Password Requirements settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('password_requirements_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'password_requirements.admin.inc',
    'weight' => 20,
  );
  return $items;
}

/**
 * Menu callback for AJAX password check.
 */
function password_requirements_ajax_check() {
  // Prevent this page from being cached.
  backdrop_page_is_cacheable(FALSE);

  // Get all the post data.
  $token = $_POST['token'] ?? FALSE;
  $password = $_POST['password'] ?? '';
  $uid = (int) $_POST['uid'] ?? 0;
  $username = $_POST['username'] ?? '';
  // Exit if we don't have a token.
  if (!$token) {
    backdrop_json_output(FALSE);
    return;
  }
  $password = urldecode($password);
  $username = urldecode($username);

  // Disallow POSTs larger than 256 characters as minor protection against DOS.
  if (strlen($password) > 256) {
    backdrop_json_output(FALSE);
    return;
  }
  // Provide account as context for password strength.
  $account = user_load($uid);

  $key = 'password_requirements:' . $account->uid;

  // If a username is not provided by the form (e.g. 'user_pass_reset_form'),
  // then we can get it from the $account object.
  if (!$username) {
    $username = $account->name;
  }

  // Validate token.
  if ($account->uid && !backdrop_valid_token($token, $key, TRUE)) {
    backdrop_json_output(FALSE);
    return;
  }

  // Get the results.
  $check_results = password_requirements_check($password, $username);
  $output = array();
  // Loop through each group of checks and start building the output array.
  foreach ($check_results['checks'] as $group_name => $check_group) {
    $output[$group_name] = array(
      'data' => ucwords($group_name),
      'children' => array(),
    );
    // Loop through all checks in the group and prepare the data for output.
    foreach ($check_group as $check_key => $check_data) {
      // Get the check result and use it to set the icon and a class for the
      // result.
      $check_result = $check_data['result'];
      $icon = $check_result ? 'check' : 'x';
      $check_result_class = $check_result ? 'result-pass' : 'result-fail';

      // Get the requirement text.
      $requirement = $check_data['check_requirement'];

      // Combine the icon and text in a span with the relevant classes.
      $check_text = '<span class="requirement-result ' . $check_result_class . '">' . icon($icon) . ' ' . $requirement . '</span>';

      // If the check failed, add the failure explanation as a single item in a
      // sub list.
      if (!$check_result) {
        $check_failure_explanation = $check_data['check_failure_explanation'];
        $check_text .= '<ul class="check-failure-explanation"><li>' . $check_failure_explanation . '</li></ul>';
      }

      // Add the check text (and failure explanation) as a child of the group.
      $output[$group_name]['children'][] = $check_text;
    }
  }
  // Convert the output array to the form needed for `theme_item_list()`.
  $items = array();
  foreach ($output as $key => $item) {
    $items[] = $item;
  }

  // Render the output as an item list with classes to help with styling.
  $check_output = theme('item_list', array(
    'items' => $items,
    'attributes' => array('class' => 'password-requirements-ul'),
    'wrapper_attributes' => array('class' => 'password-requirements'),
  ));
  $result = array(
    'overall_result' => $check_results['result'],
    'check_output' => $check_output,
  );

  backdrop_json_output($result);
}

/**
 * Gets the result of the requirements check.
 *
 * @param string $password
 *   Plain text password to be checked.
 *
 * @param string $username
 *   Username which can be checked to ensure the password does not contain it.
 *
 * @return array
 *   Result array with the following keys:
 *    - result - boolean - the overall result
 *    - checks - array - all the active checks.
 *      - requirement_group
 *        - check_key - string - the array key path of the check config.
 *          - result - boolean - pass (TRUE) or fail (FALSE)
 *          - check_requirement - string - the requirement with the number in a
 *            human readable statement.
 *          - check_failure_explanation - string - A human readable explanation
 *            of why the check failed including any relevant result or
 *            requirement metrics.
 */
function password_requirements_check($password, $username) {

  // Get the active groups.
  $active_checks = password_requirements_active_checks();
  if (isset($active_checks['exclusions']['past_passwords']) && !user_load_by_name($username)) {
    unset($active_checks['exclusions']['past_passwords']);
    if (empty($active_checks['exclusions'])) unset($active_checks['exclusions']);
  }
  $module_path = backdrop_get_path('module', 'password_requirements');
  $overall_result = TRUE;
  $results = array();
  foreach ($active_checks as $group => $checks) {
    // Load the files for group.
    include_once $module_path . '/includes/password_requirements.' . $group . '.inc';
    foreach ($checks as $check => $check_config) {
      $check_function = 'password_requirements_' . $group . '_' . $check . '_check';
      if (function_exists($check_function)) {
        $check_parameters = array(
          'password' => $password,
          'username' => $username,
          'config' => $check_config,
        );
        $check_result = call_user_func_array($check_function, $check_parameters);
        $results[$group][$check] = $check_result;
        if (!$check_result['result']) {
          $overall_result = FALSE;
        }
      }
      else {
        backdrop_set_message(t('Check function (@function_name) could not be found', array(
          '@function_name' => $check_function,
        )), 'error');
      }
    }
  }
  return array(
    'result' => $overall_result,
    'checks' => $results,
  );
}


/**
 * Implements hook_form_alter().
 */
function password_requirements_form_alter(&$form, &$form_state, $form_id) {
  // List the forms where we will modify the password field.
  $password_forms = array(
    'user_register_form',
    'user_profile_form',
    'user_pass_reset_form',
  );
  // Check if this form is in the list.
  if (in_array($form_id, $password_forms)) {
    // Get the password field and the account object.
    switch ($form_id) {
      case 'user_pass_reset_form':
        $element = &$form['pass'];
        $account = $form['#account'];
        break;
      case 'user_profile_form':
      case 'user_register_form':
        $element = &$form['account']['pass'];
        $account = $form['#user'];
    }
    // Attach the Javascript file and settings to the field.
    password_requirements_password_field_js_attach($element, $account);
    // Add icons to use for tick (check) and cross against each requirement.
    backdrop_add_icons(array(
      'x',
      'check',
    ));
    // Add validation handler to the form.
    $form['#validate'][] = 'password_requirements_form_password_validate';
  }

}

/**
 * Validation handler for password field.
 */
function password_requirements_form_password_validate($form, &$form_state) {
  // Get the password.
  $password = $form_state['values']['pass'] ?? NULL;

  // If password field is empty or NULL, password is not being changed, so exit
  // validation.
  if (empty($password)) {
    return;
  }

  // Get the account object.
  $form_id = $form['#form_id'];
  switch ($form_id) {
    case 'user_pass_reset_form':
      $account = $form['#account'];
      break;
    case 'user_profile_form':
    case 'user_register_form':
      $account = $form['#user'];
  }
  // If the account object is anonymous, get the username from the form.
  $username = empty($account->name) ? $form_state['values']['name'] : $account->name;

  // Get the results and display a form error if the password does not meet
  // requirements.
  $check_results = password_requirements_check($password, $username);
  if ($check_results['result'] == FALSE) {
    form_set_error('pass', t("Password does not meet the requirements. Verify that all the requirements are met before submitting the form again."));
  }
}

/**
 * Implements hook_user_password_reject_weak_alter().
 *
 * If this setting has been activated, it could lead to failed validation if
 * the password requirements set don't equal the same level. This is unlikely,
 * but the confusion it could create means it is best to ensure that this module
 * handles all the password requirements and validation.
 */
function password_requirements_user_password_reject_weak_alter(&$reject_weak, $account) {
  $reject_weak = FALSE;
}

/**
 * Attach JS password check to a form element.
 *
 * @param array &$element
 *   The password form element being manipulated.
 * @param object $account
 *   User account setting password.
 */
function password_requirements_password_field_js_attach(array &$element, $account) {

  // Disable the Backdrop strength meter.
  $element['#password_strength'] = FALSE;

  // Add a class so the JavaScript can reliably find the password field.
  $element['#attributes'] = array(
    'class' => array('password-field'),
  );

  $js_settings = array();
  $uid = $account->uid ?? 0;
  $username = $account->name;

  $key = 'password_requirements:' . $uid;

  $js_settings['uid'] = $uid;
  $js_settings['token'] = backdrop_get_token($key);
  $js_settings['username'] = $username;
  $js_settings['secure_base_url'] = url(NULL, array(
    'absolute' => TRUE,
    'https' => TRUE,
    'purl' => array('disabled' => TRUE))
  );

  // Attach password strength check JS.
  $element['#attached']['css'][] = backdrop_get_path('module', 'password_requirements') . '/css/password_requirements.css';
  $element['#attached']['js'][] = array(
    'data' => array('passwordRequirements' => $js_settings),
    'type' => 'setting',
  );
  $element['#attached']['js'][] = array(
    'data' => backdrop_get_path('module', 'password_requirements') . '/js/password_requirements.js',
    'weight' => 10,
  );

}

/**
 * Helper to determine which requirements check are active and get the config.
 *
 * @return array
 *   An array of checks that are active within each group and the config for
 *   each check in the format $checks['group']['check'] = array(config itams).
 */
function password_requirements_active_checks() {
  // Get the module config.
  $config = config('password_requirements.settings');

  // Define the requirement groups. Add to this array if additional groups are
  // added.
  $requirement_groups = array(
    'characters',
    'exclusions',
    'strength',
  );

  // Loop through the groups and checks to see which are active and collect the
  // config for active checks.
  $checks = array();
  foreach ($requirement_groups as $group) {
    // Get the config for each group.
    $group_config = $config->get('requirements.' . $group);
    // Loop through the checks in the group.
    foreach ($group_config as $check => $check_config) {
      // If the check is active, get all the config apart from the active
      // setting.
      if ($check_config['active']) {
        $checks[$group][$check] = $check_config;
        unset($checks[$group][$check]['active']);
      }
    }
  }
  return $checks;
}

/**
 * Implements hook_user_insert().
 */
function password_requirements_user_insert($account) {
  if (!empty($account->pass) && $account->uid) {
    // Store the user's first password in the password history.
    password_requirements_store_password($account->uid, $account->pass);
  }
}

/**
 * Implements hook_user_presave().
 *
 * Adds entry to password history when password is changed for a user. This
 * should work whether the password is changed via the User module forms or
 * programmatically via user_save().
 */
function password_requirements_user_presave($account) {
  // Check that this is not a new account.
  if (!empty($account->pass) && empty($account->is_new)) {
    // Retrieve the password from the 'original' sub object.
    $original_password = $account->original->pass;
    // Get the password from the main user object.
    $new_password = $account->pass;

    if ($original_password != $new_password) {
      // If the new password is different from the original, then the password
      // has changed and we need to store the hash of the new one.
      password_requirements_store_password($account->uid, $account->pass);
    }
  }
}

/**
 * Implements hook_user_delete().
 */
function password_requirements_user_delete($account) {
  // If the user is deleted we can remove all password history records.
  db_delete('password_requirements_password_history')
    ->condition('uid', $account->uid)
    ->execute();
}

/**
 * Store user passwords (hashed) for the history.
 *
 * @param string $user_id
 *   The 'uid' of the user.
 * @param string $password
 *   The hashed password of the user.
 */
function password_requirements_store_password($user_id, $password) {
  db_insert('password_requirements_password_history')
    ->fields(array(
      'uid' => $user_id,
      'pass' => $password,
      'created' => REQUEST_TIME,
    ))
    ->execute();
}
